// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MDG.TargetProcess.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GetUsers")]
    public partial class GetUsersFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GetUsers.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "GetUsers", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Получение списка только активных пользователей")]
        [NUnit.Framework.CategoryAttribute("Позитивный")]
        public virtual void ПолучениеСпискаТолькоАктивныхПользователей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Получение списка только активных пользователей", new string[] {
                        "Позитивный"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("Класс TP инициализирован", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 8
 testRunner.When("Я не указываю параметров при вызове метода GetUsers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 9
 testRunner.Then("Метод возвращает только активных пользователей", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 10
 testRunner.And("Количество пользователей больше одного", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Получение списка всех пользователей")]
        public virtual void ПолучениеСпискаВсехПользователей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Получение списка всех пользователей", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("Класс TP инициализирован", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 14
 testRunner.When("Я указываю параметр <includeInActive> как True метода GetUsers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 15
 testRunner.Then("Метод возвращает и активных и неактивных пользователей", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 16
 testRunner.And("Количество пользователей больше одного", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
